var GameEvent = {
    ACTIVATE_QUESTION: 'ACTIVATE_QUESTION',
    CONTINUE: 'CONTINUE_GAME',
    GAME_OVER: 'GAME_OVER',
    CLEANUP_SCOREBOARD: 'CLEANUP_SCOREBOARD',
    SHOW_TEAM_PERFORMANCE: 'SHOW_TEAM_PERFORMANCE',
    REMOVE_TEAM_PERFORMANCE: 'REMOVE_TEAM_PERFORMANCE',
    SHOW_QUESTION_FEEDBACK: 'SHOW_QUESTION_FEEDBACK',
    CLEAR_QUESTION_FEEDBACK: 'CLEAR_QUESTION_FEEDBACK',
    SOUND_COMPLETED:'SOUND_COMPLETED'
};

export default GameEvent